apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: alon-k8s-com-tls
spec:
  secretName: alon-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alon-k8s.com
  dnsNames:
    - alon-k8s.com
    - www.alon-k8s.com
